name: "APT Repo Management"
description: "Setup and manage APT repo, transferring it over SCP"
inputs:
  repo_supported_arch:
    description: "Newline-delimited list of supported architecture"
    required: true
  repo_supported_version:
    description: "Newline-delimited list of supported (linux) version"
    required: true
  file:
    description: "Newline-delimited list of .deb files"
    required: true
  file_target_version:
    description: "Newline-delimited list of version target of supplied .deb file"
    required: true
  public_key:
    description: "GPG public key for apt repo"
    required: false
  private_key:
    description: "GPG private key for signing apt repo"
    required: true
  key_passphrase:
    description: "Passphrase of GPG private key"
    required: false
  repo_folder:
    description: "Location of APT repo folder relative to root of Github pages"
    required: false
    default: "repo"
  scp_hostname:
    description: "Hostname for the SCP server"
    required: true
  scp_port:
    description: "Port for the SCP server"
    required: false
    default: "22"
  scp_username:
    description: "SCP username for authentication"
    required: true
  apt_repo_private:
    description: "Path to the private key for SCP authentication"
    required: true
  remote_file_path:
    description: "Remote file path to transfer the .deb file"
    required: true
  debug:
    description: "Print debug log"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "package"
  color: "green"
