name: "APT Repo Management"
description: "Setup and manage APT repo, transferring it over SCP"
inputs:
  repo_supported_arch:
    description: "Newline-delimited list of supported architecture"
    required: true
  repo_supported_version:
    description: "Newline-delimited list of supported (linux) version"
    required: true
  file:
    description: "Newline-delimited list of .deb files"
    required: true
  public_key:
    description: "GPG public key for apt repo"
    required: false
  private_key:
    description: "GPG private key for signing apt repo"
    required: true
  key_passphrase:
    description: "Passphrase of GPG private key"
    required: false
  scp_hostname:
    description: "Hostname for the SCP server"
    required: true
  scp_port:
    description: "Port for the SCP server"
    required: false
    default: "22"
  apt_repo_private:
    description: "Path to the private key for SCP authentication"
    required: true
  remote_file_path:
    description: "Remote file path to transfer the .deb file"
    required: true
  debug:
    description: "Print debug log"
    required: false
  use_ssh_agent:
    description: "Enable SSH agent forwarding for SCP authentication"
    required: false
    default: "true"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    SSH_AUTH_SOCK: ${{ github.action_path }}/ssh-agent.sock
branding:
  icon: "package"
  color: "green"
